/**
 * Paquete de idioma espanol (es) para el texto de cliente de DeepSeek Harness.
 *
 * Generado por tools/build-client.ts — no editar a mano; editar
 * data/es-dictionaries.json y regenerar.
 */
window.__ModuleLoader__.load({
  id: "dsh-locale-es",
  factory: () => {
    const module = { exports: {} }
    const exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" })
    exports.inject = ["locale"]
    exports.apply = function apply(ctx) {
      ctx.effect(
        () => ctx.locale.addLanguage({ id: "es", label: "Español", fallback: "en" }),
        "dsh-locale-es: language",
      )
      const dictionaries = {
  "approval": {
    "allowOnce": "Permitir una vez",
    "detail.aria": "Detalles de la aprobación",
    "escalation": "La herramienta {toolName} solicita ejecución privilegiada",
    "reject": "Rechazar",
    "waiting": "Esperando aprobación"
  },
  "chat": {
    "chat.deepDiving": "Explorando a fondo…",
    "chat.loadError": "No se pudo cargar el historial: {message} ({code})",
    "chat.loadingHistory": "Cargando el historial…",
    "chat.loadOlder": "Cargar anteriores",
    "chat.toBottom": "Ir al final",
    "chat.turnNavigation.jump": "Ir al turno {turn}",
    "chat.turnNavigation.jumpLoad": "Cargar e ir al turno {turn}",
    "chat.turnNavigation.label": "Navegación por turnos",
    "chat.turnNavigation.turn": "Turno {turn}",
    "clock.md": "{m}/{d}",
    "clock.ymd": "{y}-{m}-{d}",
    "command.done": "Completado",
    "command.failed": "El comando falló",
    "command.running": "Ejecutando…",
    "command.title": "Comando",
    "duration.compactMinutes": "{minutes}m{seconds}s",
    "duration.compactSeconds": "{seconds}s",
    "duration.hours": "{hours}h {minutes}m {seconds}s",
    "duration.milliseconds": "{milliseconds}ms",
    "duration.minutes": "{minutes}m {seconds}s",
    "duration.seconds": "{seconds}s",
    "fileOpen.title": "No se pudo abrir el archivo",
    "fileOpen.unknown": "No se pudo abrir este archivo",
    "json.truncated": "… truncado, {total} caracteres en total",
    "message.branch": "Ramificar en una conversación nueva",
    "message.branchUnavailable": "Disponible solo en el último mensaje de un turno completado",
    "message.compaction": "Contexto compactado",
    "message.compaction.commandTitle": "compact",
    "message.compaction.completed": "Se compactaron {items} elementos del historial (~{tokens} tokens)",
    "message.compaction.expand": "Ver el resumen de compactación",
    "message.compaction.running": "Compactando el contexto…",
    "message.compaction.unavailable": "Resumen de compactación no disponible",
    "message.context.catalog.more": "… {count} más",
    "message.context.catalog.replaced": "Catálogo de reemplazos",
    "message.context.instructions.added": "agregado",
    "message.context.instructions.loaded": "cargado",
    "message.context.instructions.removed": "eliminado",
    "message.context.instructions.updated": "actualizado",
    "message.context.recall.counts": "{retained} conservados · {omitted} omitidos",
    "message.context.recall.truncated": "truncado",
    "message.context.relay.from": "Desde la sesión {session}",
    "message.context.snapshot.supersedes": "Reemplaza instantáneas anteriores",
    "message.contextInjection": "Inyección de contexto",
    "message.contextRecall": "Recuperación de sesión",
    "message.extraBlock": "Bloque de contenido adicional",
    "message.failure.auth": "La clave de API no es válida",
    "message.maxTokens": "Se alcanzó el límite de tokens de salida",
    "message.maxTokens.hint": "La respuesta se cortó; la salida anterior se conserva en la conversación. Envía «continuar» para que el modelo retome.",
    "message.ranFor": "Duró {duration}",
    "message.referenceSeparator": ", ",
    "message.referenceSummary": "Sesión referenciada · {labels}",
    "message.retry.active": "Reintentando la petición",
    "message.retry.cancelled": "Reintento cancelado",
    "message.retry.delay": "Retraso del reintento: ",
    "message.retry.failure": "Motivo del fallo: ",
    "message.retry.scheduled": "Esperando para reintentar la petición",
    "message.retry.started": "Se reintentó la petición",
    "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}s",
    "message.stopped": "Detenido",
    "message.systemPrompt": "Prompt del sistema",
    "message.systemPromptUpdate": "Actualización del prompt",
    "message.think": "Pensar",
    "message.tokensPerSecond": "{tps} tok/s",
    "message.turnError": "Este turno falló",
    "message.turnProcess.messages.one": "{count} mensaje",
    "message.turnProcess.messages.other": "{count} mensajes",
    "message.turnProcess.separator": " · ",
    "message.turnProcess.subagents.one": "{count} subagente",
    "message.turnProcess.subagents.other": "{count} subagentes",
    "message.turnProcess.thoughtForAWhile": "Pensó un rato",
    "message.turnProcess.toolCalls.one": "{count} tool call",
    "message.turnProcess.toolCalls.other": "{count} tool calls",
    "message.turnTime.duration": "Tiempo total de ejecución",
    "message.turnTime.speed": "Tokens por segundo (TPS)",
    "message.turnTime.title": "Tiempo y velocidad del turno",
    "message.turnTime.ttft": "Tiempo hasta el primer token (TTFT)",
    "message.turnUsage.cacheHit": "Aciertos de caché",
    "message.turnUsage.cacheRead": "Entrada en caché",
    "message.turnUsage.cacheWrite": "Escritura en caché",
    "message.turnUsage.consumed": "Uso {total}",
    "message.turnUsage.count": "{count} tok",
    "message.turnUsage.input": "Entrada sin caché",
    "message.turnUsage.model": "Proveedor / modelo",
    "message.turnUsage.output": "Salida",
    "message.turnUsage.reasoning": " ({tokens} de razonamiento)",
    "message.turnUsage.title": "Uso del turno",
    "message.unknownBlock": "Bloque de contenido desconocido",
    "message.unknownSurface": "Evento de superficie desconocido: {type}",
    "number.groupSeparator": ",",
    "row.failed": "Falló",
    "row.running": "En ejecución",
    "settings.transcript.compact": "Compacto",
    "settings.transcript.description": "Controla el contenido del proceso en los turnos completados",
    "settings.transcript.normal": "Normal",
    "settings.transcript.title": "Visualización de la conversación",
    "stats.cacheHit": "Aciertos de caché {percent}%",
    "stats.counts": "{turns} turnos {steps} pasos",
    "stats.dialog.llmTime": "Tiempo del LLM",
    "stats.dialog.speed": "Tokens por segundo (TPS)",
    "stats.dialog.title": "Estadísticas de la sesión",
    "stats.dialog.toolTime": "Tiempo de tools",
    "stats.dialog.ttft": "Tiempo medio hasta el primer token (TTFT)",
    "stats.dialog.usageTitle": "Uso de tokens",
    "view.chat": "Chat"
  },
  "command": {
    "description.compact": "Compactar el historial de conversación anterior",
    "description.export": "Descargar el registro de esta sesión como archivo ZIP",
    "description.feedback": "Registrar comentarios sobre esta sesión",
    "description.goal": "Definir o ver el objetivo de una tarea prolongada",
    "description.permission": "Cambiar el preset de permisos (modo sandbox + política de aprobación)",
    "description.plan": "Entrar o salir del modo plan",
    "label.compact": "Compactar",
    "label.export": "Exportar",
    "label.feedback": "Comentarios",
    "label.goal": "Objetivo",
    "label.permission": "Permisos",
    "label.plan": "Plan",
    "listbox.aria": "Coincidencias de /{command}",
    "notice.attachmentsUnsupported": "/{command} no acepta archivos adjuntos; quitalos primero",
    "overlay.aria": "Opciones de /{command}",
    "search.aria": "Filtrar opciones",
    "search.placeholder": "Buscar…",
    "section.add": "Agregar",
    "section.commands": "Comandos",
    "status.applying": "Aplicando…",
    "status.empty": "Sin opciones",
    "status.loading": "Cargando opciones…",
    "token.compact": "compact",
    "token.export": "export",
    "token.feedback": "feedback",
    "token.goal": "goal",
    "token.permission": "permission",
    "token.plan": "plan"
  },
  "common": {
    "back": "Atrás",
    "brand.localBuild": "Compilación local de DSH",
    "cancel": "Cancelar",
    "close": "Cerrar",
    "collapse": "Contraer",
    "copied": "Copiado",
    "copy": "Copiar",
    "copy.compactJson": "Copiar JSON compacto",
    "copy.failed": "No se pudo copiar",
    "copy.json": "Copiar JSON",
    "copy.optionsHint": "{action}; clic derecho para opciones de copia",
    "copy.path": "Copiar ruta de la propiedad",
    "copy.prettyJson": "Copiar JSON con formato",
    "copy.value": "Copiar valor",
    "delete": "Eliminar",
    "edit": "Editar",
    "expand": "Expandir",
    "json.collapseNode": "Contraer nodo JSON",
    "json.expandNode": "Expandir nodo JSON",
    "json.label": "JSON",
    "load.failed": "No se pudo cargar",
    "loading": "Cargando…",
    "markdown.footnotes": "Notas al pie",
    "markdown.truncatedCharacters": "… truncado en {total} caracteres",
    "more": "Más",
    "next": "Siguiente",
    "none": "Ninguno",
    "number.million": "{value}M",
    "number.thousand": "{value}K",
    "ok": "Aceptar",
    "previous": "Anterior",
    "retry": "Reintentar",
    "save": "Guardar",
    "search": "Buscar",
    "skip": "Omitir",
    "submit": "Enviar",
    "submitting": "Enviando…",
    "truncated": "Truncado",
    "unknown": "Desconocido"
  },
  "conversation": {
    "access.confirm.acknowledge": "Entiendo los riesgos y quiero continuar",
    "access.confirm.cancel": "Cancelar",
    "access.confirm.description": "El acceso total reduce los pasos de confirmación y permite que el agente realice más acciones directamente, incluidas operaciones sensibles, cambios en archivos o comandos externos. Úsalo solo cuando confíes en la tarea actual.",
    "access.confirm.enable": "Activar el acceso total",
    "access.confirm.title": "¿Activar el acceso total?",
    "access.preset.fullAccess": "Acceso total",
    "access.preset.readOnly": "Solo lectura",
    "access.preset.workspaceWrite": "Escritura en el workspace",
    "ask.answered": "{answered}/{total} respondidas",
    "ask.cancelled": "cancelada",
    "ask.cancelledDetail": "Este conjunto de preguntas se canceló antes de enviar las respuestas.",
    "ask.interrupted": "interrumpida",
    "ask.interruptedDetail": "Este conjunto de preguntas se interrumpió antes de enviar las respuestas.",
    "ask.rowTitle": "Hacer una pregunta",
    "ask.skipped": "Sin responder",
    "ask.waiting": "esperando",
    "attachment.dropBlocked": "No se pueden agregar archivos ni imágenes en este momento",
    "attachment.dropDesc": "Límite de imágenes: hasta {count} imágenes, {size} cada una",
    "attachment.dropTitle": "Arrastra archivos o imágenes aquí para agregarlos",
    "attachment.pending": "Adjuntos pendientes",
    "attachment.scrollLeft": "Desplazar a la izquierda",
    "attachment.scrollRight": "Desplazar a la derecha",
    "bash.failed": "Falló",
    "bash.running": "En ejecución",
    "bash.stopped": "Detenido",
    "command.attachmentsUnsupported": "/{command} no acepta archivos adjuntos; quítalos primero",
    "context.aria": "{percent} del contexto usado",
    "context.messages": "Mensajes",
    "context.system": "Prompt del sistema",
    "context.tools": "Definiciones de herramientas",
    "context.used": "del contexto usado",
    "details.running": "Ejecutando…",
    "diff.collapseAria": "Contraer el diff",
    "diff.expandAria": "Expandir {count} líneas más del diff",
    "diff.expandRest": "… {count} líneas más",
    "diff.files.one": "{count} archivo",
    "diff.files.other": "{count} archivos",
    "file.label": "Archivo",
    "file.notStaged": "El archivo aún no terminó de subirse; vuelve a agregarlo e inténtalo de nuevo",
    "file.pending": "Archivos pendientes",
    "file.remove": "Quitar el archivo {name}",
    "file.retry": "Reintentar subir {name}",
    "file.sessionUnavailable": "Sesión no disponible; no se pueden subir archivos",
    "file.stillUploading": "Los archivos se están subiendo; envía cuando terminen",
    "file.uploadFailed": "Falló la subida; haz clic para reintentar",
    "file.uploading": "Subiendo…",
    "hero.chooseWorkspace": "Elegir workspace",
    "hero.headline": "Hacia lo desconocido",
    "hero.preview": "Vista previa",
    "hint.goal": "describe el objetivo de una tarea prolongada",
    "hint.goal.active": "objetivo activo — editar / pausar / reanudar / borrar",
    "hint.plan": "describe tu tarea para generar un plan",
    "image.closePreview": "Cerrar vista previa",
    "image.dimensionTooLarge": "Los lados de la imagen deben medir como máximo {size}px; redúcela e inténtalo de nuevo",
    "image.fileTooLarge": "Cada imagen debe pesar menos de {size}",
    "image.label": "Imagen",
    "image.loadFailed": "No se pudo cargar la imagen; haz clic para reintentar",
    "image.loading": "Cargando la imagen…",
    "image.modelUnsupported": "El modelo actual no admite imágenes; cambia a uno que sí",
    "image.openOriginal": "Ver original",
    "image.openOriginalLabel": "{label}, haz clic para ver el original",
    "image.original": "Imagen original",
    "image.pending": "Imágenes pendientes",
    "image.preview": "Vista previa de la imagen",
    "image.remove": "Quitar la imagen {name}",
    "image.sendFailed": "No se pudieron enviar las imágenes ({reason}); vuelve a agregarlas e inténtalo de nuevo",
    "image.tooMany": "Un mensaje puede incluir hasta {count} imágenes",
    "image.tooManyPixels": "La resolución de la imagen es demasiado alta; comprímela e inténtalo de nuevo",
    "image.totalTooLarge": "Las imágenes superan {size} en total; quita algunas e inténtalo de nuevo",
    "image.unsupportedType": "Solo se admiten imágenes PNG, JPG, WebP y GIF",
    "input.accessMode": "Modo de acceso, actual: {name}",
    "input.commands": "Agregar archivos o ejecutar comandos",
    "input.file": "Archivo",
    "input.send": "Enviar mensaje",
    "input.send.queue": "Poner el mensaje en cola",
    "input.send.steer": "Guiar el mensaje",
    "input.stop": "Detener la generación",
    "placeholder.default": "Envía un mensaje o ejecuta una tarea, / comandos, @ archivos o sesiones",
    "placeholder.hero": "Describe lo que quieres crear, / comandos, @ archivos o sesiones",
    "placeholder.parentOffline": "La sesión principal está desconectada; no se puede enviar, pero sí detener la ejecución",
    "placeholder.plan": "describe tu tarea para generar un plan",
    "placeholder.steerQueue": "Cmd/Ctrl+Enter guía todos los mensajes en cola",
    "placeholder.unavailable": "Sesión no disponible",
    "placeholder.workspace": "Elige un workspace para empezar",
    "queue.cancelEdit": "Cancelar la edición",
    "queue.count": "{n} mensajes en cola",
    "queue.edit": "Editar el mensaje en cola",
    "queue.edit.unsupported": "Contiene contenido que no es texto; editar aún no es compatible",
    "queue.editFailed": "Falló la edición: puede que este mensaje ya haya empezado a enviarse.",
    "queue.file": "Archivo en cola {name}",
    "queue.image": "Imagen del mensaje en cola",
    "queue.remove": "Quitar el mensaje en cola",
    "queue.removeFailed": "Falló la eliminación: puede que este mensaje ya haya empezado a enviarse.",
    "queue.save": "Guardar el mensaje en cola",
    "queue.sending": "Enviando…",
    "queue.steer": "Guiar el mensaje en cola",
    "queue.steer.unavailable": "Guiar solo está disponible mientras el agente se ejecuta",
    "queue.steerFailed": "Falló la guía. Inténtalo de nuevo.",
    "read.collapseAria": "Contraer el contenido",
    "read.expandAria": "Expandir {count} líneas más",
    "read.expandRest": "… {count} líneas más",
    "read.window": "Mostrando {shown} de {total} líneas",
    "row.failed": "Falló",
    "row.input": "ENT",
    "row.inspect": "Inspeccionar",
    "row.output": "SAL",
    "row.running": "En ejecución",
    "row.stopped": "Detenido",
    "search.collapseAria": "Contraer los resultados",
    "search.expandAria": "Expandir {count} líneas de resultados más",
    "search.expandRest": "… {count} líneas más",
    "search.matches": "{shown} coincidencias · {files} archivos",
    "search.matches.truncated": "Mostrando {shown} de {total} coincidencias · {files} archivos",
    "search.noResults": "Sin resultados",
    "search.paths": "{shown} rutas",
    "search.paths.truncated": "Mostrando {shown} de {total} rutas",
    "session.hierarchy": "Jerarquía de sesiones",
    "settings.enter.description": "Qué hacen Enter y el botón Enviar mientras el agente se ejecuta; Cmd/Ctrl+Enter usa el otro comportamiento",
    "settings.enter.queue": "Cola",
    "settings.enter.steer": "Guiar",
    "settings.enter.title": "Envío mientras el agente trabaja",
    "terminal.collapseAria": "Contraer la salida",
    "terminal.done": "Listo",
    "terminal.exitCode": "código de salida {code}",
    "terminal.expandAria": "Expandir las {n} líneas de salida restantes",
    "terminal.expandRest": "… {n} líneas más",
    "terminal.failed": "Falló",
    "terminal.noOutput": "Sin salida",
    "terminal.running": "En ejecución",
    "terminal.sendInput": "(enviar entrada)",
    "terminal.session": "Terminal {sessionId}",
    "terminal.signal": "señal {signal}",
    "todo.completed": "{done}/{total} completadas",
    "todo.progress.active": "{active} en curso",
    "todo.progress.done": "{done} completadas",
    "todo.progress.pending": "{pending} pendientes",
    "todo.rowTitle": "Actualizar la lista de tareas",
    "todo.title": "Tareas",
    "tool.title.bash": "Bash",
    "tool.title.code": "Code",
    "tool.title.edit": "Edit",
    "tool.title.generic": "Tool call",
    "tool.title.glob": "Glob",
    "tool.title.grep": "Grep",
    "tool.title.inspect": "Inspect",
    "tool.title.pwsh": "Pwsh",
    "tool.title.read": "Read",
    "tool.title.readImage": "Leer imagen",
    "tool.title.removeCordis": "Quitar el plugin de Cordis",
    "tool.title.runCordis": "Ejecutar el plugin de Cordis",
    "tool.title.search": "Search",
    "tool.title.stopCordis": "Detener el plugin de Cordis",
    "tool.title.webFetch": "Fetch",
    "tool.title.webSearch": "Search",
    "tool.title.write": "Write",
    "web.contentTruncated": "Contenido truncado",
    "web.http": "HTTP",
    "web.noResults": "No se encontraron resultados",
    "web.sourcesTruncated": "Lista de fuentes truncada"
  },
  "deliverables": {
    "presented.action": "Abrir",
    "presented.all": "Los {count} archivos",
    "presented.collapse": "Contraer",
    "presented.collapseAria": "Contraer los archivos entregados",
    "presented.defaultApp": "Abrir con app por defecto",
    "presented.directory": "Abrir la carpeta contenedora",
    "presented.directoryError": "No se pudo abrir la carpeta contenedora. Inténtalo de nuevo.",
    "presented.directoryOpened": "Se solicitó abrir la carpeta contenedora",
    "presented.directoryOpening": "Abriendo la carpeta contenedora…",
    "presented.error": "No se pudo abrir. Haz clic para reintentar.",
    "presented.expandAria": "Mostrar los {count} archivos entregados",
    "presented.explorer": "Mostrar en Explorador",
    "presented.file": "Archivo",
    "presented.finder": "Mostrar en el Finder",
    "presented.hostError": "No se pudo leer la información de escritorio del Host",
    "presented.more": "Más acciones de archivo para {name}",
    "presented.nativeUnavailable": "Este archivo no tiene una ruta disponible en el Host. Previsualízalo en la barra lateral.",
    "presented.opened": "Abierto en la app por defecto",
    "presented.opening": "Abriendo…",
    "presented.preview": "Vista previa",
    "presented.previewButton": "Abrir {name} en la barra lateral",
    "presented.previewCard": "Vista previa de {name}",
    "presented.retry": "Reintentar",
    "presented.revealed": "Se solicitó mostrar en el gestor de archivos",
    "presented.revealError": "No se pudo mostrar en el gestor de archivos. Inténtalo de nuevo.",
    "presented.revealing": "Mostrando en el gestor de archivos…",
    "presented.unavailable": "Este Host no tiene un escritorio disponible para abrir archivos o carpetas",
    "produced.label": "Archivos modificados",
    "produced.more": "+ {count} archivos",
    "produced.moreOne": "+ 1 archivo",
    "produced.open": "Abrir {name}",
    "row.error": "Falló la entrega",
    "row.inspect": "Inspeccionar la llamada",
    "row.ok": "Entregado",
    "row.running": "Entregando",
    "row.stopped": "Interrumpido",
    "row.title": "Presentar archivos"
  },
  "documentHtml": {
    "failed": "No se pudo previsualizar este documento HTML.",
    "frame": "Vista previa del documento HTML",
    "loading": "Preparando la vista previa de HTML…",
    "title": "HTML"
  },
  "documentMarkdown": {
    "code.copied": "Copiado",
    "code.copy": "Copiar",
    "footnotes": "Notas al pie",
    "viewer.label": "Markdown"
  },
  "feedback": {
    "action.dislike": "Respuesta mala",
    "action.dislikeActive": "Quitar la valoración",
    "action.like": "Respuesta buena",
    "action.likeActive": "Quitar la valoración",
    "category.instruction-following": "Comprensión y seguimiento de instrucciones",
    "category.other": "Otro",
    "category.product-interaction": "Funciones del producto e interacción",
    "category.resource-cost": "Uso de recursos y costo",
    "category.security-privacy-permission": "Seguridad, privacidad y permisos",
    "category.service-stability": "Estabilidad y velocidad",
    "category.task-result": "Resultado de la tarea",
    "dialog.categories": "Categoría de los comentarios",
    "dialog.detail": "Detalles de los comentarios",
    "dialog.hint": "Agrega detalles para ayudarnos a mejorar. Tu envío incluirá el registro de la conversación actual.",
    "dialog.title": "Enviar comentarios",
    "error.conflict": "Estos comentarios cambiaron en otro lugar; se muestra el estado más reciente",
    "error.generic": "No se pudieron guardar",
    "error.load": "No se pudieron cargar",
    "error.noteTooLarge": "La descripción es demasiado larga; acórtala y envía de nuevo",
    "toast.recorded": "Gracias por tus comentarios"
  },
  "goal": {
    "action.cancel": "Cancelar edición",
    "action.clear": "Borrar objetivo",
    "action.edit": "Editar objetivo",
    "action.pause": "Pausar objetivo",
    "action.resume": "Reanudar objetivo",
    "action.save": "Guardar objetivo",
    "commandInput.aria": "Entrada de comando",
    "objective.aria": "Objetivo",
    "phase.active": "Objetivo en curso",
    "phase.active.disarmed": "Objetivo inactivo",
    "phase.blocked": "Objetivo bloqueado",
    "phase.paused": "Objetivo en pausa"
  },
  "job": {
    "count.idle.one": "{count} tarea en segundo plano",
    "count.idle.other": "{count} tareas en segundo plano",
    "count.live.one": "{count} tarea en ejecución",
    "count.live.other": "{count} tareas en ejecución",
    "duration.hours": "{hours} h {minutes} min",
    "duration.minutes": "{minutes} min {seconds} s",
    "duration.seconds": "{seconds} s",
    "duration.title.done": "Duró {duration}",
    "duration.title.live": "En ejecución desde hace {duration}",
    "list.aria": "Tareas en segundo plano",
    "status.completed": "completada",
    "status.failed": "fallida",
    "status.killed": "cancelada",
    "status.running": "en ejecución",
    "status.stopping": "deteniéndose"
  },
  "model": {
    "action.reload": "Recargar",
    "blocked.composer": "Este modelo no está disponible — selecciona uno para continuar",
    "command.description": "Selecciona el modelo para esta conversación",
    "command.label": "Modelo",
    "effort.providerDefault": "Por defecto",
    "empty.efforts": "Este modelo no ofrece niveles de esfuerzo de razonamiento.",
    "empty.models": "No hay modelos disponibles.",
    "error.action": "Falló la operación del modelo: {message}",
    "menu.aria": "Modelo y esfuerzo de razonamiento",
    "menu.effort": "Esfuerzo",
    "menu.model": "Modelo",
    "option.deepseekV4Flash.description": "Rápido, eficiente y económico; ideal para tareas puntuales, rutinarias o en paralelo.",
    "option.deepseekV4Pro.description": "Programación con agentes, conocimiento y razonamiento difícil más potentes; ideal para tareas complejas o críticas para la calidad, con un costo mayor.",
    "option.loadError": "No se pudo cargar el catálogo: {message}",
    "status.loading": "Actualizando la lista de modelos…",
    "trigger.aria": "Seleccionar modelo, actual {model}",
    "trigger.ariaEffort": "Seleccionar modelo, actual {model}, esfuerzo de razonamiento {effort}",
    "trigger.fallback": "Seleccionar modelo",
    "trigger.loading": "Cargando los modelos…",
    "trigger.selectAria": "Seleccionar modelo",
    "warning.groupLoad": "{name} no se pudo cargar: {message}"
  },
  "open-in-app": {
    "app.androidstudio": "Android Studio",
    "app.cursor": "Cursor",
    "app.explorer": "Explorador de archivos",
    "app.filemanager": "Archivos",
    "app.finder": "Finder",
    "app.fork": "Fork",
    "app.ghostty": "Ghostty",
    "app.gitbash": "Git Bash",
    "app.github": "GitHub Desktop",
    "app.gitkraken": "GitKraken",
    "app.gnometerminal": "GNOME Terminal",
    "app.goland": "GoLand",
    "app.intellij": "IntelliJ IDEA",
    "app.iterm": "iTerm2",
    "app.kitty": "kitty",
    "app.konsole": "Konsole",
    "app.phpstorm": "PhpStorm",
    "app.pycharm": "PyCharm",
    "app.rider": "Rider",
    "app.rustrover": "RustRover",
    "app.smartgit": "SmartGit",
    "app.sourcetree": "Sourcetree",
    "app.sublimemerge": "Sublime Merge",
    "app.sublimetext": "Sublime Text",
    "app.terminal": "Terminal",
    "app.tower": "Tower",
    "app.vscode": "VS Code",
    "app.vscodeinsiders": "VS Code Insiders",
    "app.warp": "Warp",
    "app.webstorm": "WebStorm",
    "app.windowsterminal": "Windows Terminal",
    "app.windsurf": "Windsurf",
    "app.xcode": "Xcode",
    "app.zed": "Zed",
    "menu.aria": "Abrir en",
    "menu.toggle": "Elegir una aplicación para abrir",
    "open.error": "No se pudo abrir",
    "open.title": "Abrir el workspace en {app}",
    "open.tooltip": "Abrir localmente"
  },
  "plan": {
    "chip.exitFailed": "No se pudo salir del modo plan",
    "chip.label": "Plan",
    "chip.off.aria": "Modo plan desactivado, presiona para activarlo",
    "chip.off.title": "Modo plan desactivado — haz clic para activarlo (/plan)",
    "chip.on.aria": "Modo plan activado, presiona para desactivarlo",
    "chip.on.title": "Modo plan activado — haz clic para desactivarlo (/plan off)"
  },
  "question": {
    "action.next": "Siguiente",
    "action.skip": "Omitir esta pregunta",
    "custom.placeholder": "Escribe tu respuesta",
    "error.incomplete": "Completa esta pregunta primero.",
    "error.unanswered": "Selecciona una opción o escribe una respuesta personalizada.",
    "nav.cancel": "Descartar todas las preguntas",
    "nav.maximize": "Expandir la tarjeta de pregunta",
    "nav.minimize": "Contraer la tarjeta de pregunta",
    "nav.next": "Pregunta siguiente",
    "nav.prev": "Pregunta anterior",
    "option.recommended": "Recomendado",
    "plan.approve": "Aprobar",
    "plan.decline": "Rechazar",
    "plan.discuss": "Conversar sobre esto",
    "plan.header": "Revisión del plan"
  },
  "reference": {
    "candidate.noCwd": "(sin cwd)",
    "crumb.root": "Workspace",
    "section.files": "Archivos y carpetas",
    "section.sessions": "Sesiones",
    "time.days": "{n}d",
    "time.hours": "{n}h",
    "time.minutes": "{n}min",
    "time.months": "{n}mes",
    "time.now": "ahora",
    "time.years": "{n}a"
  },
  "schedule.catalog": {
    "frequency.every": "Cada {value} {unit}",
    "frequency.once": "Una vez",
    "list.aria": "Recordatorios activos",
    "relative.future": "en {value} {unit}",
    "relative.now": "Vence ahora",
    "relative.overdue": "vencido hace {value} {unit}",
    "status.overdue": "Vencido",
    "status.scheduled": "Programado",
    "trigger.one": "{count} recordatorio",
    "trigger.other": "{count} recordatorios",
    "unit.day.one": "día",
    "unit.day.other": "días",
    "unit.hour.one": "hora",
    "unit.hour.other": "horas",
    "unit.minute.one": "minuto",
    "unit.minute.other": "minutos",
    "unit.second.one": "segundo",
    "unit.second.other": "segundos"
  },
  "settings": {
    "close": "Cerrar",
    "connection.connected": "Conectado",
    "connection.connecting": "Reconectando",
    "connection.error": "Sin conexión",
    "connection.reconnect": "Sin conexión, reconectar ahora",
    "connection.restart": "Reconectando automáticamente, reconectar ahora",
    "connection.retry": "Reconectar ahora",
    "general.nav": "General",
    "openDocument": "Abrir archivo de configuración",
    "openDocument.error": "No se pudo abrir el archivo de configuración",
    "title": "Ajustes",
    "trigger": "Ajustes"
  },
  "settings.agentPreset": {
    "brokenBadge": "No se pudo cargar",
    "brokenNoCopy": "Un preset que no se pudo cargar no se puede duplicar",
    "builtIn": "Integrado",
    "builtInGroup": "Integrados",
    "cancel": "Cancelar",
    "close": "Cerrar",
    "composition": "Composición (agent.cordis.yml)",
    "copyIntro": "El preset se copia completo en esta máquina. El identificador será el nombre de su carpeta y no se puede cambiar; lo demás se edita en los archivos del preset.",
    "copyOf": "Copiado de",
    "copyTitle": "Duplicar preset",
    "create": "Crear",
    "creating": "Creando…",
    "creatorDraft": "Redactar un preset personalizado con el modo Creador",
    "customGroup": "Personalizados",
    "delete": "Eliminar",
    "deleteConfirm": "Eliminar",
    "deleteDescription": "Se elimina la carpeta del preset. Las sesiones que ya corren con él siguen funcionando; las nuevas no pueden seleccionarlo.",
    "deleteTitle": "¿Eliminar este preset?",
    "deleting": "Eliminando…",
    "displayName": "Nombre",
    "displayNamePlaceholder": "Se muestra en el selector; por defecto usa el identificador",
    "duplicate": "Duplicar",
    "duplicateUnavailable": "No hay carpeta de presets escribible",
    "enablePickerToCreate": "Activa la selección de modo de agente para usar el modo Creador",
    "enablePickerToSetDefault": "Activa la selección de modo de agente para elegir uno por defecto",
    "error": "No se pudieron cargar los presets.",
    "headerHint": "El preset de agente que usa esta sesión, fijado al iniciarla",
    "idInvalid": "Usa letras minúsculas, dígitos y guiones, empezando con una letra o un dígito.",
    "idRequired": "Dale un identificador al preset.",
    "idTaken": "Ya existe un preset con este identificador.",
    "inUse": "Predeterminado",
    "nav": "Presets de agente",
    "noDescription": "Sin descripción",
    "openLocation": "Abrir carpeta",
    "presetCordisDescription": "Pensado para crear presets de agente propios, con todas las capacidades del modo Estándar más inspección en runtime, experimentos con plugins y guía para redactar presets.",
    "presetCordisName": "Modo Creador",
    "presetId": "Identificador",
    "presetIdPlaceholder": "my-agent",
    "presetMinimalDescription": "Agente de programación de una sola tool con un shell persistente.",
    "presetMinimalName": "Modo Mínimo",
    "presetPtcDescription": "Agente de programación completo sin la tool de workflows; las demás tools se exponen por el SDK del modo PTC para que el modelo combine pasos en un programa TypeScript.",
    "presetPtcName": "Modo PTC",
    "presetStandardDescription": "Agente de programación completo con edición de archivos, shell, búsqueda de archivos y web, skills, planificación, objetivos, subagentes y workflows.",
    "presetStandardName": "Modo Estándar",
    "retry": "Reintentar",
    "revealedPathLabel": "Archivos del preset:",
    "seatHint": "Preset de agente para la sesión que estás por iniciar",
    "sectionIntro": "Un preset es la composición de plugins con la que corre el agente de una sesión: sus tools, su prompt y sus capacidades. Duplica uno existente, o deja que el agente redacte uno por ti en el modo Creador.",
    "selectionOffDefault": "Por defecto",
    "setDefault": "Predeterminar",
    "showLocation": "Mostrar la ubicación",
    "showPicker": "Permitir cambiar de modo de agente",
    "showPickerBeta": "Beta",
    "showPickerDescription": "Con esto activado, las tareas nuevas pueden elegir los modos Estándar, PTC, Creador, Mínimo y propios. Desactivado, todas usan el modo por defecto (Estándar salvo configuración). Solo afecta a tareas nuevas.",
    "switchRefused": "No se pudo cambiar a {name}: {reason}",
    "userTrust": "Personalizado",
    "view": "Ver"
  },
  "settings.locale": {
    "language.title": "Idioma"
  },
  "settings.models": {
    "add": "Agregar proveedor",
    "addModel": "Agregar modelo",
    "advancedHint": "Los demás campos están en settings.yaml; edita esa sección directamente.",
    "apply": "Aplicar",
    "applying": "Aplicando…",
    "baseUrl": "URL base",
    "baseUrlDefault": "Por defecto del proveedor",
    "cancel": "Cancelar",
    "close": "Cerrar",
    "conflict": "Otra persona cambió estos ajustes mientras esta tarjeta estaba abierta. Ciérrala y vuelve a abrirla para editar los valores actuales.",
    "contextWindow": "Ventana de contexto",
    "contextWindowPlaceholder": "Usa el default del proveedor",
    "create": "Crear proveedor",
    "creating": "Creando…",
    "credentialConfigured": "Clave de API configurada",
    "credentialMissing": "Falta la clave de API",
    "customAdd": "Agregar proveedor propio",
    "customApi": "Protocolo de API",
    "customApiUnset": "Sin elegir",
    "customBaseUrlInvalid": "Ingresa una URL HTTP o HTTPS válida.",
    "customBaseUrlPlaceholder": "https://gateway.example/v1",
    "customDisplayName": "Nombre visible",
    "customized": "Ajustes personalizados",
    "customNeedsBaseUrl": "Un proveedor personalizado necesita una URL base.",
    "customNeedsModels": "Un proveedor personalizado necesita al menos un modelo.",
    "customRoute": "ID del proveedor",
    "customRouteHint": "Identificador en minúsculas, que empieza con una letra, que nombra de forma única a este proveedor en las solicitudes y como nombre de su credencial.",
    "customRouteInvalid": "Empieza con una letra minúscula; luego letras minúsculas, dígitos y guiones.",
    "customRouteTaken": "Ya hay un proveedor que usa este ID.",
    "customTag": "Personalizado",
    "customTitle": "Proveedor personalizado",
    "deleteConfirm": "Eliminar {provider}",
    "deleteDescription": "Eliminar {provider} borra su configuración. La credencial que use se administra en otro lugar y se conservará.",
    "deleteDescriptionWithCredential": "Eliminar {provider} borra su configuración y la clave de API almacenada.",
    "deleteTitle": "¿Eliminar {provider}?",
    "deleting": "Eliminando {provider}…",
    "edit": "Editar",
    "editProvider": "Editar {provider}",
    "fetchAdopt": "Agregar",
    "fetchDescription": "Estos son los modelos disponibles de este proveedor. Elige los que quieras agregar.",
    "fetchDeselectAll": "Deseleccionar todo",
    "fetchEmpty": "El proveedor no informó ningún modelo. Agrégalos a mano.",
    "fetching": "Consultando al proveedor…",
    "fetchModels": "Obtener los modelos disponibles",
    "fetchNeedsBaseUrl": "Ingresa primero la URL base y después obtén los modelos.",
    "fetchNoMatches": "No hay modelos coincidentes.",
    "fetchSearch": "Buscar modelos",
    "fetchSelectAll": "Seleccionar todo",
    "fetchTitle": "Elige los modelos que agregar",
    "intro": "Ingresa tus claves de API para usar los modelos de los siguientes proveedores.",
    "keyBlank": "Ingresa la clave de API, o deja el campo vacío para conservar la almacenada.",
    "keyBlankNew": "Ingresa la clave de API, o deja el campo vacío si este proveedor se autentica de otra forma.",
    "keyEnvLocked": "Proporcionada por el entorno de inicio (solo lectura)",
    "keyIllegalCharacters": "Esta clave de API no tiene un formato válido. Verifícala.",
    "keyInput": "Clave de API",
    "keyPlaceholder": "Ingresa tu clave de API",
    "keyPlaceholderNative": "Ingresa una clave de API, o déjalo vacío para usar la autenticación del entorno",
    "keyRequired": "Ingresa una clave de API para continuar.",
    "keyStored": "Configurada — ingresa un valor nuevo para reemplazarla",
    "loadFailed": "No se pudo cargar el directorio de proveedores",
    "maxTokens": "Tokens máximos de salida",
    "maxTokensPlaceholder": "Usa el default del proveedor",
    "model": "Modelo",
    "modelAdvanced": "Capacidades",
    "modelCapacityInvalid": "Una capacidad debe ser un número, con el sufijo opcional K o M.",
    "modelContextInvalid": "La ventana de contexto debe ser un número positivo, como 131072, 256K o 1M.",
    "modelContextWindow": "Ventana de contexto",
    "modelDuplicate": "Cada ID de modelo, una sola vez.",
    "modelId": "ID del modelo",
    "modelIdDuplicate": "El ID del modelo debe ser único.",
    "modelIdRequired": "El ID del modelo es obligatorio.",
    "modelMaxTokens": "Tokens máximos de salida",
    "modelMaxTokensInvalid": "Los tokens máximos de salida deben ser un número positivo, como 8192, 64K o 1M.",
    "modelName": "Nombre visible",
    "modelNameInvalid": "El nombre visible no puede estar vacío.",
    "modelNamePlaceholder": "Usa el ID del modelo cuando está vacío",
    "models": "Modelos",
    "modelsCustomized": "Catálogo de modelos propio",
    "modelsEmpty": "No se mostrará ningún modelo en el selector. Los ID no listados aún pueden enviarse directamente.",
    "modelsInherited": "Usando los defaults del adaptador",
    "nav": "Modelos",
    "onboardingDescription": "Configura el proveedor oficial de DeepSeek para empezar a crear.",
    "onboardingLater": "Configurar más tarde",
    "onboardingSave": "Guardar y continuar",
    "onboardingSaving": "Guardando…",
    "onboardingTitle": "Agrega una clave de API para empezar",
    "provider": "Proveedor",
    "readOnly": "Ajustes de solo lectura en esta instalación.",
    "remove": "Eliminar",
    "removeModel": "Eliminar modelo",
    "removeProvider": "Eliminar {provider}",
    "resetModels": "Restaurar por defecto",
    "retry": "Reintentar",
    "savedProvider": "Se guardó {provider}.",
    "settingsPathUnresolvable": "ruta de ajustes no resoluble",
    "title": "Modelos",
    "welcomeBody": "DeepSeek Harness 0.1 sigue en pruebas para desarrolladores de Harness. Muchas áreas necesitan mejoras y agradecemos los comentarios de la comunidad de desarrolladores. Los plugins principales y las API fundamentales de DeepSeek Harness seguirán evolucionando rápidamente en los próximos meses.\n\nEsperamos explorar los límites de la inteligencia junto a desarrolladores de todo el mundo, sobre una infraestructura de código abierto, abierta, reutilizable y componible. Invitamos a desarrolladores de Harness de todo el mundo a sumarse al ecosistema de plugins de DSH.",
    "welcomeContinue": "Continuar",
    "welcomeError": "No se pudo guardar la confirmación. Inténtalo de nuevo.",
    "welcomeTitle": "Aviso de pruebas internas"
  },
  "settings.permission": {
    "confirm.acknowledge": "Entiendo los riesgos y quiero continuar",
    "confirm.cancel": "Cancelar",
    "confirm.description": "El acceso total permite que las sesiones nuevas reduzcan los pasos de confirmación y realicen más acciones directamente, incluidas operaciones sensibles, cambios en archivos o comandos externos. Úsalo solo cuando confíes en las tareas siguientes.",
    "confirm.enable": "Activar el acceso total",
    "confirm.title": "¿Activar el acceso total?",
    "description": "Elige el modo de permisos por defecto para las sesiones nuevas",
    "loading": "Cargando",
    "preset.fullAccess": "Acceso total",
    "preset.readOnly": "Solo lectura",
    "preset.workspaceWrite": "Escritura en el workspace",
    "title": "Permisos",
    "unavailable": "No disponible"
  },
  "settings.pluginInventory": {
    "active": "En ejecución",
    "condition": "Deshabilitado cuando",
    "conditionalTag": "Condicional",
    "configuration": "Configuración",
    "countUnit": "plugins",
    "disabledTag": "Deshabilitado",
    "empty": "No hay plugins disponibles.",
    "emptySearch": "Sin coincidencias.",
    "enabledIn": "Habilitado en",
    "enabledTag": "Habilitado",
    "error": "Los plugins no están disponibles temporalmente.",
    "failed": "No se pudo iniciar",
    "failedCountLabel": "fallidos",
    "failedTag": "Falló",
    "fromPreset": "De",
    "globalSubtitle": "Del sistema y de todas las sesiones",
    "globalTitle": "Plugins globales",
    "loading": "Leyendo los plugins…",
    "loadingPhase": "Cargando",
    "matchesInOtherPresets": "{count} coincidencias más en otros presets: ",
    "moduleLabel": "Módulo",
    "pending": "Esperando dependencias",
    "presetEnabledTag": "Habilitado mediante presets",
    "presetOptionBroken": "{name} (no se pudo cargar)",
    "presetOptionDefault": "{name} (por defecto)",
    "presetProvidedDetail": "Deshabilitado globalmente; los presets de agente lo aportan por sesión",
    "presetSubtitle": "Los aporta el preset de cada sesión",
    "presetTitle": "Plugins de sesión",
    "retry": "Reintentar",
    "runtime": "Estado",
    "search": "Buscar plugins",
    "switcherLabel": "Elige el preset de agente que inspeccionar",
    "tab": "Lista de plugins",
    "unloading": "Descargando",
    "unobserved": "No se está ejecutando",
    "viewInPreset": "Ver en el grupo de presets"
  },
  "settings.plugins": {
    "agentLoopDescription": "Cómo despacha el agente las tool calls.",
    "agentLoopMaxParallel": "Tool calls en paralelo",
    "agentLoopMaxParallelHint": "Máximo de llamadas seguras en paralelo dentro de un paso.",
    "agentLoopTitle": "Bucle del agente",
    "bashDescription": "Limita todos los comandos que ejecuta el agente.",
    "bashMaxOutputBytes": "Límite de salida por flujo (bytes)",
    "bashMaxOutputBytesHint": "La salida que supera este límite pasa a un archivo temporal en lugar de perderse.",
    "bashTimeoutMs": "Tiempo límite por comando (ms)",
    "bashTimeoutMsHint": "Cuánto puede ejecutarse un comando antes de que se termine.",
    "bashTitle": "Shell",
    "collapse": "Ocultar los ajustes",
    "configurableTab": "Configuración del plugin",
    "discard": "Descartar",
    "empty": "Esta instalación no expone ajustes de plugins.",
    "expand": "Mostrar los ajustes",
    "intro": "Configura e inspecciona los plugins instalados.",
    "invalidNumber": "Ingresa un número, o deja el campo vacío para usar el valor por defecto.",
    "nav": "Plugins",
    "overridden": "Anulado",
    "readOnly": "Ajustes de solo lectura en esta instalación.",
    "reset": "Restablecer por defecto",
    "save": "Guardar",
    "saveFailed": "La instalación no aceptó estos valores; corrígelos.",
    "saving": "Guardando…",
    "subagentModelSelectionAllowed": "Modelos que los agentes pueden elegir",
    "subagentModelSelectionChoose": "Los agentes pueden elegir proveedor, modelo y esfuerzo de reasoning para cada subagente entre los modelos autorizados. Solo aplica a sesiones nuevas.",
    "subagentModelSelectionConflict": "Los ajustes cambiaron en otro lugar. Descarta tu borrador e inténtalo de nuevo.",
    "subagentModelSelectionDescription": "Controla qué modelos pueden elegir los agentes para los subagentes.",
    "subagentModelSelectionEmpty": "Ningún proveedor de modelos anuncia modelos por ahora.",
    "subagentModelSelectionLoadFailed": "No se pudieron cargar los modelos.",
    "subagentModelSelectionLoading": "Cargando los modelos…",
    "subagentModelSelectionOff": "Los subagentes usan los defaults configurados o heredan el modelo del agente principal. Las elecciones guardadas se conservan.",
    "subagentModelSelectionPartial": "No se pudieron cargar algunos proveedores de modelos; las elecciones guardadas se pueden seguir quitando.",
    "subagentModelSelectionRequired": "Selecciona al menos un modelo antes de guardar.",
    "subagentModelSelectionRetry": "Reintentar",
    "subagentModelSelectionTitle": "Subagente",
    "subagentModelSelectionToggle": "Permitir que los agentes elijan modelos para los subagentes",
    "subagentModelSelectionUnavailable": "No disponible por ahora",
    "subagentModelSelectionUnavailableGroup": "Guardado pero no disponible por ahora",
    "tabs": "Vistas de plugins",
    "title": "Plugins",
    "unsaved": "Sin guardar",
    "webSearchApiKey": "Clave de API",
    "webSearchApiKeyHint": "Se almacena fuera del archivo de ajustes. Deja el campo vacío para conservar la clave actual.",
    "webSearchApiKeySet": "Hay una clave configurada.",
    "webSearchApiKeyUnset": "No hay ninguna clave configurada; la búsqueda no está disponible hasta que haya una.",
    "webSearchBaseUrl": "Endpoint",
    "webSearchBaseUrlHint": "Deja el campo vacío para usar el valor por defecto del proveedor.",
    "webSearchDescription": "El proveedor de búsqueda de DeepSeek.",
    "webSearchMaxUses": "Máximo de búsquedas por solicitud",
    "webSearchMaxUsesHint": "Cuántas veces puede buscar una solicitud antes de tener que responder.",
    "webSearchTitle": "Búsqueda en la web"
  },
  "settings.theme": {
    "appearance.dark": "Oscuro",
    "appearance.light": "Claro",
    "appearance.system": "Sistema",
    "appearance.title": "Apariencia",
    "fontSize.decrease": "Reducir el tamaño de fuente",
    "fontSize.description": "Solo afecta el contenido de la conversación",
    "fontSize.increase": "Aumentar el tamaño de fuente",
    "fontSize.title": "Tamaño de fuente",
    "fontSize.unit": "px"
  },
  "sidebar": {
    "panels.label": "Paneles globales",
    "session.new": "Nueva sesión",
    "session.new.label": "Nueva sesión",
    "toggle.collapse": "Contraer la barra lateral",
    "toggle.open": "Abrir la barra lateral"
  },
  "sidebarCodePreview": {
    "copied": "Copiado",
    "copy": "Copiar",
    "title": "Código"
  },
  "sidebarDocumentPreview": {
    "changed": "El archivo cambió; se muestra el contenido anterior.",
    "error.notFound": "No se encontró el archivo. Puede que se haya movido o eliminado.",
    "error.notRegularFile": "No es un archivo normal; no hay nada que mostrar.",
    "error.notText": "No es un archivo de texto; la vista previa no está disponible por ahora.",
    "error.tooLarge": "Esta página supera el límite de {limit} y no se puede leer.",
    "error.unavailable": "Falló la lectura: {message}",
    "loading": "Leyendo…",
    "loadMore": "Cargar más",
    "openWith": "Abrir con",
    "reload": "Volver a leer el archivo",
    "reloadNow": "Recargar",
    "rendererUnavailable": "La vista previa de {name} no está disponible.",
    "resourceUnavailable": "El servicio de recursos de archivos no está disponible.",
    "retry": "Reintentar",
    "viewer.text": "Texto sin formato",
    "wrap.aria": "Ajuste de línea",
    "wrap.disable": "Desactivar el ajuste de línea",
    "wrap.enable": "Activar el ajuste de línea"
  },
  "sidebarFiles": {
    "empty": "Directorio vacío",
    "entry.other": "No es un archivo ni un directorio, así que no se puede abrir.",
    "error.notDirectory": "Eso no es un directorio.",
    "error.notFound": "Ese directorio ya no existe. Puede que se haya movido o eliminado.",
    "error.outsideWorkspace": "Ese directorio está fuera del workspace, así que la barra lateral no lo leerá.",
    "error.unavailable": "Falló la lectura: {message}",
    "guide.description": "Explora los archivos del workspace de esta sesión",
    "guide.title": "Archivos del workspace",
    "loading": "Leyendo…",
    "noWorkspace": "Esta sesión no tiene directorio de workspace.",
    "reload": "Recargar",
    "truncated": "Hay demasiadas entradas; solo se muestran algunas.",
    "type.label": "Archivos"
  },
  "sidebarImage": {
    "failed": "No se pudo mostrar esta imagen.",
    "loading": "Abriendo la imagen…",
    "preview": "Vista previa de la imagen: {name}",
    "title": "Imagen",
    "unsupported": "La vista previa de imagen requiere el contenido completo del archivo."
  },
  "sidebarPdf": {
    "failed": "No se puede mostrar el PDF: {message}",
    "loading": "Abriendo el PDF…",
    "pageImage": "Página {page} del PDF",
    "password": "Este PDF requiere contraseña; las vistas previas protegidas con contraseña no son compatibles.",
    "rendering": "Renderizando la página…",
    "retry": "Reintentar",
    "title": "PDF",
    "unsupported": "La vista previa de PDF requiere el contenido completo del archivo.",
    "workerFailed": "El proceso de renderizado del PDF no pudo continuar. Vuelve a intentarlo."
  },
  "sidebarRight": {
    "chrome.collapse": "Contraer la barra lateral",
    "chrome.collapseAria": "Contraer la barra lateral derecha",
    "chrome.exitFullscreen": "Salir de pantalla completa",
    "chrome.expand": "Abrir la barra lateral",
    "chrome.expandAria": "Abrir la barra lateral derecha",
    "chrome.toFullscreen": "Pantalla completa",
    "dock.addTab": "Nueva pestaña",
    "dock.closeFloat": "Cerrar",
    "dock.closeTab": "Cerrar",
    "dock.dockFloat": "Devolver a la barra lateral",
    "dock.drop.bottom": "Agregar división inferior",
    "dock.drop.center": "Mover aquí",
    "dock.drop.left": "Agregar división izquierda",
    "dock.drop.right": "Agregar división derecha",
    "dock.drop.top": "Agregar división superior",
    "dock.emptyPane": "Panel vacío",
    "dock.splitPane": "Dividir",
    "dock.splitPaneDisabled": "El límite es de dos paneles",
    "dock.splitPaneNarrow": "No hay ancho suficiente para dividir; ensancha la barra lateral",
    "tab.guide.title": "Inicio",
    "tab.unavailable": "Todavía no hay nada aquí que pueda ver este tipo de contenido."
  },
  "skill": {
    "menu.userOnly": "solo usuario",
    "row.failed": "No se pudo cargar la habilidad",
    "row.inspect": "Inspeccionar",
    "row.instructions": "Instrucciones",
    "row.running": "Cargando habilidad",
    "row.stopped": "Carga de habilidad detenida",
    "row.title": "Habilidad"
  },
  "slash.menu": {
    "command": "Comandos",
    "crumbs.aria": "Navegación de carpetas",
    "drill.aria": "Explorar carpeta",
    "drill.hint": "Explorar carpeta",
    "drill.key": "Tab",
    "loading": "Cargando…",
    "skill": "Habilidades",
    "subagent": "Subagentes",
    "suggestions.aria": "Sugerencias de activación"
  },
  "subagent": {
    "activity.inactive": "no se está ejecutando",
    "activity.running": "en ejecución",
    "branch.collapse": "Contraer los descendientes de {label}",
    "branch.expand": "Expandir los descendientes de {label}",
    "count.running.one": "{count} subagente en ejecución",
    "count.running.other": "{count} subagentes en ejecución",
    "count.total.one": "{count} subagente",
    "count.total.other": "{count} subagentes",
    "diagnostic.corrupt": "registro de sesión dañado",
    "diagnostic.unavailable": "registro de sesión no disponible temporalmente",
    "diagnostic.unsupported": "versión de registro de subagente no compatible",
    "duration.days": "{days}d",
    "duration.daysHours": "{days}d {hours}h",
    "duration.exactDays": "{days}d {hours}h {minutes}m {seconds}s",
    "duration.exactTitle": "Duración activa total: {duration}",
    "duration.hours": "{hours}h {minutes}m {seconds}s",
    "duration.minutes": "{minutes}m {seconds}s",
    "duration.months": "~{months}mes",
    "duration.monthsDays": "~{months}mes {days}d",
    "duration.seconds": "{seconds}s",
    "duration.years": "~{years}a",
    "duration.yearsMonths": "~{years}a {months}mes",
    "load.error": "No se pudieron cargar los subagentes",
    "loading.aria": "Cargando los subagentes",
    "loading.label": "Cargando los subagentes…",
    "mode.continuable": "continuable",
    "mode.oneShot": "de un solo uso",
    "readonly.body": "La sesión principal está desconectada; vuelve a abrirla para seguir enviando mensajes.",
    "readonly.oneShot.body": "Las tareas de un solo uso no aceptan seguimiento; aquí está el registro completo de la ejecución.",
    "readonly.oneShot.title": "Registro de subagente de un solo uso",
    "readonly.title": "Este subagente es de solo lectura por ahora",
    "retry": "Reintentar",
    "switcher.aria": "Cambiar de subagente: {title}",
    "tokens.million": "{value}M",
    "tokens.thousand": "{value}K",
    "tokens.total": "{value} tok",
    "tree.aria": "Sesiones de subagentes"
  },
  "trajectory": {
    "block.label": "Bloque #{index} {type}",
    "block.openSummary": "Abrir el resumen de tool calls del bloque #{index}",
    "block.openSummaryTitle": "Abrir el resumen de tool calls",
    "column.input": "Entrada",
    "column.model": "Modelo",
    "column.output": "Salida",
    "column.think": "Pensar",
    "column.time": "Tiempo",
    "column.tools": "Herramientas",
    "details.assistantMessage": "Mensaje del asistente",
    "details.close": "Cerrar los detalles",
    "details.compacted": "Compactado",
    "details.error": "Error",
    "details.event": "Detalles del evento",
    "details.failure.auth": "La clave de API no es válida",
    "details.hierarchy": "Jerarquía",
    "details.model": "Modelo",
    "details.provider": "Proveedor",
    "details.purpose": "Propósito",
    "details.resize": "Redimensionar detalles",
    "details.resizeTitle": "Arrastra para redimensionar. Doble clic para restablecer.",
    "details.result": "Resultado",
    "details.retry": "Reintento",
    "details.retryDelay": "Retraso del reintento",
    "details.scheduled": "Programado",
    "details.source": "Origen",
    "details.status": "Estado",
    "details.subtoolCalls": "Llamadas a subherramientas",
    "details.toolCall": "Tool call",
    "details.toolCalls": "Tool calls",
    "group.compaction": "Compactación {seq}",
    "group.message": "Mensaje",
    "group.step": "Paso {step}",
    "history.clickToLoadEarlier": "Haz clic para cargar el historial anterior",
    "history.loadEarlier": "Cargar el historial anterior",
    "history.loadingEarlier": "Cargando el historial anterior…",
    "history.loadingEarlierAria": "Cargando el historial anterior…",
    "history.loadingTrajectory": "Cargando la trayectoria…",
    "kind.assistant": "ASISTENTE",
    "kind.compacted": "COMPACTADO",
    "kind.context": "CONTEXTO",
    "kind.message": "Mensaje",
    "kind.sub": "Sub",
    "kind.subtool": "SUBHERRAMIENTA",
    "kind.system": "SISTEMA",
    "kind.tool": "HERRAMIENTA",
    "kind.user": "USUARIO",
    "layout.compacted": "Contexto compactado",
    "layout.compacting": "Compactando el contexto…",
    "layout.compactionFailed": "Falló la compactación",
    "layout.compactionInterrupted": "La compactación se interrumpió antes de terminar.",
    "layout.fileAttachments": "Archivos ×{count}",
    "layout.imageOnly": "Imágenes ×{count}",
    "layout.initialSystemPrompt": "Prompt del sistema inicial",
    "layout.systemPromptAndToolsUpdated": "Prompt del sistema y herramientas actualizados",
    "layout.systemPromptUpdated": "Prompt del sistema actualizado",
    "layout.toolCallOnly": "Solo tool call",
    "layout.toolsUpdated": "Herramientas actualizadas",
    "options.json": "JSON de opciones de la solicitud",
    "options.notRecorded": "Opciones no registradas",
    "record.json": "JSON",
    "record.namedParametersJson": "JSON de parámetros de {name}",
    "record.noContent": "Sin contenido",
    "record.noOutput": "Sin salida",
    "record.noPayload": "No se capturó ningún payload",
    "record.noResult": "No se capturó ningún resultado",
    "record.outputJson": "JSON del resultado",
    "record.parameters": "Parámetros",
    "record.parametersJson": "JSON de parámetros",
    "record.payloadJson": "JSON del payload",
    "record.resultJson": "JSON del resultado",
    "record.schemaUnavailable": "Esquema no disponible",
    "record.systemPrompt": "Prompt del sistema",
    "record.systemPromptMissing": "Esta solicitud no tiene prompt del sistema",
    "record.thinking": "Pensando",
    "record.toolCallOnly": "(solo tool call)",
    "record.tools": "Herramientas",
    "record.toolsMissing": "Esta solicitud no tiene herramientas",
    "request.collapsedAssistant": "asistente",
    "request.collapsedSummary": "Resumen de {kind} contraído, {summary}",
    "request.collapsedTurn": "turno",
    "request.compaction": "Compactación · {section}",
    "request.compactionPurpose": "Compactación",
    "request.label": "Solicitud #{request}",
    "request.labelCompaction": "Solicitud #{request} · Compactación",
    "request.noContent": "sin contenido",
    "request.retryProgress": "{retry} de {maximum}",
    "request.rowAria": "{request}{kind}, {content}",
    "request.rowAriaCompaction": "Solicitud {request}, compactación",
    "request.rowPrefix": "Solicitud {request}, ",
    "section.betweenTurns": "Entre turnos",
    "source.goal": "Objetivo",
    "source.goalRound": "Objetivo · Ronda {round}",
    "source.messageJson": "JSON del origen del mensaje",
    "source.notRecorded": "Origen no registrado",
    "source.plugin": "Plugin",
    "source.pluginNamed": "Plugin · {plugin}",
    "source.unknown": "Desconocido",
    "source.user": "Usuario",
    "status.completed": "Completado",
    "status.failed": "Falló",
    "status.pending": "Pendiente",
    "summary.steps.one": "{count} paso",
    "summary.steps.other": "{count} pasos",
    "summary.toolCalls.one": "{count} tool call",
    "summary.toolCalls.other": "{count} tool calls",
    "tab.diff": "Diff",
    "tab.options": "Opciones",
    "tab.payload": "Payload",
    "tab.preview": "Vista previa",
    "tab.raw": "Sin procesar",
    "tab.rawOutput": "Salida sin procesar",
    "tab.result": "Resultado",
    "tab.schema": "Esquema",
    "tab.source": "Origen",
    "tab.summary": "Resumen",
    "tab.systemPrompt": "Prompt del sistema",
    "tab.timing": "Tiempos",
    "tab.tools": "Herramientas",
    "tab.usage": "Uso",
    "timeline.aria": "Timeline de la trayectoria",
    "timeline.noTimingData": "Sin datos de tiempos",
    "timeline.overviewAria": "Vista general de la timeline; arrastra horizontalmente para enfocar eventos",
    "timeline.started": "Inicio {time}",
    "timeline.total": "Total {duration}",
    "timeline.ttftDecoding": "TTFT {ttft} · Decodificación {decoding}",
    "timing.duration": "Duración",
    "timing.durationTooShort": "Duración demasiado corta",
    "timing.firstTokenUnavailable": "Primer token no disponible",
    "timing.generation": "Generación",
    "timing.notAvailable": "No disponible",
    "timing.notRecorded": "No registrado",
    "timing.outputTokensUnavailable": "Tokens de salida no disponibles",
    "timing.request": "Tiempos de la solicitud",
    "timing.sessionTimestamps": "Marcas de tiempo de la sesión",
    "timing.sessionTimestampsRunning": "Marcas de tiempo de la sesión (en ejecución)",
    "timing.showLocalTime": "Mostrar la hora local",
    "timing.showUnixTimestamp": "Mostrar la marca de tiempo Unix",
    "timing.source": "Origen de los tiempos",
    "timing.started": "Iniciado",
    "timing.stepStartUnavailable": "Inicio del paso no disponible",
    "timing.throughput": "Rendimiento",
    "timing.totalDuration": "Duración total",
    "timing.ttft": "TTFT",
    "timing.usageUnavailable": "Uso no disponible",
    "toolbar.actualTime": "Tiempo real",
    "toolbar.aria": "Toolbar de la trayectoria",
    "toolbar.calls": "Llamadas",
    "toolbar.collapseCalls": "Contraer las llamadas",
    "toolbar.collapseTurns": "Contraer los turnos",
    "toolbar.duration": "Duración",
    "toolbar.expandCalls": "Expandir las llamadas",
    "toolbar.expandTurns": "Expandir los turnos",
    "toolbar.search": "Buscar en la trayectoria",
    "toolbar.searchPlaceholder": "Buscar",
    "toolbar.turns": "Turnos",
    "toolbar.useActualDuration": "Usar la duración real",
    "toolbar.useEqualWidth": "Usar operaciones de ancho uniforme",
    "turn.label": "Turno {turn}",
    "unit.milliseconds": "{value} ms",
    "unit.seconds": "{value} s",
    "unit.tokens": "{value} tok",
    "unit.tokensPerSecond": "{value} tok/s",
    "usage.cacheCreated": "Caché creada",
    "usage.cached": "En caché",
    "usage.content": "Contenido",
    "usage.input": "Entrada",
    "usage.notReported": "Uso no informado",
    "usage.other": "Otros",
    "usage.output": "Salida",
    "usage.reasoning": "Razonamiento",
    "usage.sessionCumulative": "Acumulado de la sesión",
    "usage.thisRequest": "Esta solicitud",
    "usage.tokens": "Tokens",
    "view.trajectory": "Trayectoria"
  },
  "workflowRun": {
    "member.empty": "Nombre de miembro vacío",
    "member.open": "Abrir {name}",
    "phase.empty": "Nombre de fase vacío",
    "phase.unassigned": "Sin fase",
    "run.empty": "No se inició ningún miembro",
    "run.members.one": "{count} miembro",
    "run.members.other": "{count} miembros",
    "run.title": "{name}",
    "status.cancelled": "Cancelado",
    "status.completed": "Completado",
    "status.failed": "Falló",
    "status.interrupted": "Interrumpido",
    "status.running": "En ejecución",
    "statusCount.cancelled": "Cancelados: {count}",
    "statusCount.completed": "Completados: {count}",
    "statusCount.failed": "Fallidos: {count}",
    "statusCount.interrupted": "Interrumpidos: {count}",
    "statusCount.running": "En ejecución: {count}"
  },
  "workspace": {
    "actions.newSession.aria": "Nueva sesión en {name}",
    "actions.session.aria": "Acciones de la sesión {name}",
    "actions.workspace.aria": "Acciones del workspace {name}",
    "conflict.named": "Ya existe un workspace llamado «{name}».",
    "date.ymd": "{y}-{m}-{d}",
    "delete.desc": "Esto quita «{name}» de la lista de workspaces. La carpeta y los registros de sesión se conservarán. Sus sesiones aparecerán en Sin agrupar.",
    "delete.pending": "Eliminando el workspace…",
    "delete.workspace": "Eliminar workspace",
    "empty.noMatches": "Sin coincidencias",
    "empty.none": "Todavía no hay sesiones",
    "field.sessionName": "Nombre de la sesión",
    "field.workspaceName": "Nombre del workspace",
    "folderError.retry": "Elegir de nuevo",
    "folderError.title": "No se pudo abrir la carpeta",
    "group.ungrouped": "Sin agrupar",
    "groupBy.flat": "En una sola lista",
    "groupBy.label": "Agrupar por",
    "groupBy.workspace": "Workspace",
    "hover.copied": "Copiado",
    "hover.created": "Creado {time}",
    "menu.addWorkspace": "Agregar workspace…",
    "menu.archiveSession": "Archivar",
    "menu.fork": "Bifurcar",
    "orderBy.label": "Ordenar por",
    "orderBy.manual": "Manual",
    "orderBy.updated": "Última actualización",
    "picker.loading": "Cargando los workspaces…",
    "rename": "Renombrar",
    "rename.session.title": "Renombrar sesión",
    "rename.workspace.title": "Renombrar workspace",
    "schedule.active": "Tiene una tarea programada activa",
    "search.clear": "Borrar la búsqueda",
    "search.hasMore": "Mostrando los primeros {n} resultados. Afina tu búsqueda.",
    "search.noMatches": "No hay sesiones coincidentes",
    "search.pending": "Buscando en el historial de sesiones…",
    "search.placeholder": "Buscar sesiones...",
    "search.results.aria": "Resultados de la búsqueda",
    "search.sessions.aria": "Buscar sesiones",
    "search.unavailable": "La búsqueda por contenido no está disponible temporalmente. Se muestran las coincidencias por nombre.",
    "section.sessions": "Sesiones",
    "section.workspaces": "Workspaces",
    "session.new": "Nueva sesión",
    "sessions.collapse": "Mostrar menos",
    "sessions.count.one": "{n} sesión",
    "sessions.count.other": "{n} sesiones",
    "sessions.expand": "Mostrar {n} sesiones más",
    "status.completed": "Completado",
    "status.idle": "Inactivo",
    "status.planReview": "Plan pendiente de revisión",
    "status.running": "En ejecución",
    "status.subagentsRunning.one": "{n} subagente en ejecución",
    "status.subagentsRunning.other": "{n} subagentes en ejecución",
    "status.waitingAnswer": "Esperando respuesta",
    "status.waitingApproval": "Esperando aprobación",
    "time.ago": "hace {t}",
    "time.days": "{n}d",
    "time.hours": "{n}h",
    "time.minutes": "{n}min",
    "time.months": "{n}mes",
    "time.now": "ahora",
    "time.years": "{n}a",
    "viewOptions.label": "Opciones de vista",
    "workspace.add": "Agregar workspace"
  },
  "directory-browser": {
    "browser.cancel": "Cancelar",
    "browser.create": "Crear",
    "browser.createIn": "Nueva carpeta en «{name}»",
    "browser.editPath": "Editar la ruta",
    "browser.folderName": "Nombre de la carpeta",
    "browser.home": "Inicio",
    "browser.loading": "Cargando…",
    "browser.newFolder": "Nueva carpeta",
    "browser.open": "Abrir",
    "browser.showHidden": "Mostrar archivos ocultos",
    "browser.title": "Seleccionar el directorio del workspace",
    "browser.truncated": "Hay demasiadas carpetas para listar; solo se muestra el principio.",
    "browser.untitledFolder": "Carpeta sin título"
  },
  "agent-team": {
    "blocked": "Bloqueado por dependencias",
    "blockedBy": "Bloqueado por",
    "blockers": "IDs de tareas bloqueantes (separados por comas)",
    "cancel": "Cancelar",
    "close": "Cerrar",
    "complete": "Completar",
    "conflict": "La tarea cambió y se recargó. Revísala antes de reintentar.",
    "create": "Nueva tarea",
    "delete": "Eliminar",
    "description": "Descripción de la tarea",
    "edit": "Editar",
    "empty": "Todavía no hay tareas compartidas",
    "loading": "Cargando el equipo…",
    "memberStatus.failed": "Falló",
    "memberStatus.idle": "Inactivo",
    "memberStatus.inactive": "Inactivo",
    "memberStatus.provisioning": "Preparándose",
    "memberStatus.running": "En ejecución",
    "model": "Modelo",
    "open": "Abrir la conversación del compañero",
    "owner": "Responsable",
    "ready": "Listo",
    "refresh": "Actualizar equipo",
    "reopen": "Reabrir",
    "roster": "Miembros",
    "save": "Guardar",
    "scopes": "Ámbitos de escritura (separados por comas)",
    "status.completed": "Completada",
    "status.in_progress": "En curso",
    "status.pending": "Pendiente",
    "subject": "Asunto de la tarea",
    "tasks": "Tareas compartidas",
    "trigger": "Equipo de agentes",
    "unowned": "Sin responsable",
    "writeScopes": "Ámbitos de escritura"
  },
  "cordis": {
    "a11y.defining": "Definiendo el plugin",
    "a11y.failed": "Falló la definición",
    "a11y.stopped": "Definición interrumpida",
    "action.approve": "Permitir",
    "action.approveOnce": "Solo esta versión",
    "action.approvePlugin": "Versiones futuras de este plugin",
    "action.decline": "Rechazar",
    "action.inspect": "Inspeccionar",
    "action.remove": "Quitar",
    "action.retry": "Reintentar",
    "action.rollback": "Revertir",
    "action.run": "Ejecutar",
    "action.stop": "Detener",
    "body.clientCode": "Cliente",
    "body.copied": "Copiado",
    "body.copy": "Copiar",
    "body.hostCode": "Host",
    "body.output": "Resultado",
    "body.source": "Código del plugin",
    "panel.approvals.aria": "Aprobaciones de Cordis",
    "panel.current": "Actual: {packageId}",
    "panel.empty": "Todavía no hay plugins definidos",
    "panel.group.current": "Esta sesión",
    "panel.group.others": "Otras sesiones",
    "panel.hint": "Los controles están en el panel de Cordis, arriba de Ajustes",
    "panel.loading": "Leyendo…",
    "panel.next": "Siguiente: {packageId}",
    "panel.plugins.aria": "Plugins de Cordis",
    "panel.readFailed": "Falló la lectura del inventario de plugins: {message}",
    "panel.runningCount": "{count} en ejecución",
    "panel.title": "Plugins de Cordis",
    "panel.trigger": "Plugin de Cordis",
    "panel.version": "Versión",
    "purpose.missing": "(sin propósito)",
    "render.failedAbdicated": "Falló el renderizado en {slot}; se restauró la UI por defecto:",
    "render.failedHeld": "Falló el renderizado en {slot}:",
    "row.defineTitle": "Registrar plugin de Cordis",
    "row.removeTitle": "Quitar plugin de Cordis",
    "row.runTitle": "Ejecutar plugin de Cordis",
    "row.stopTitle": "Detener plugin de Cordis",
    "row.updateTitle": "Actualizar plugin de Cordis",
    "run.removed": "Este paquete ya no existe",
    "run.superseded": "Abajo hay una ejecución más reciente",
    "status.awaitingApproval": "Esperando aprobación",
    "status.clientPending": "Cliente listo para activar",
    "status.failed": "Falló la ejecución",
    "status.idle": "Listo",
    "status.removed": "Quitado",
    "status.running": "En ejecución",
    "status.superseded": "Hay una ejecución más reciente"
  },
  "session-log-download": {
    "dialog.close": "Cerrar",
    "dialog.commandFailed": "No se pudo iniciar la exportación de la sesión.",
    "dialog.errorTitle": "Falló la exportación de la sesión",
    "dialog.preparingDescription": "Preparando un ZIP con esta sesión, sus subsesiones y los adjuntos.",
    "dialog.preparingTitle": "Exportando la sesión",
    "dialog.successDescription": "El navegador está descargando el ZIP de la sesión.",
    "dialog.successTitle": "Empezó la descarga de la sesión",
    "header.more": "Más acciones",
    "menu.download": "Descargar el registro de la sesión"
  }
}
      for (const ns of Object.keys(dictionaries)) {
        ctx.effect(
          () => ctx.locale.register(ns, "es", dictionaries[ns]),
          "dsh-locale-es: " + ns + " dictionary",
        )
      }
    }
    return module.exports
  },
})
